apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
data:
  MYSQL_HOST: ${MYSQL_HOST}
  MYSQL_PORT: ${MYSQL_PORT}
  MYSQL_DATABASE: ${MYSQL_DB}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_USER: ${MYSQL_USER}
  ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
  NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
