apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: root-user-password
    MYSQL_DATABASE: book_review_db
    MYSQL_USER: book_review_user
    MYSQL_PASSWORD: book_review_user_password
    JWT_SECRET: book-review-secret
